#ifndef ___MODEL_MODEL_H_H
#define ___MODEL_MODEL_H_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char melodic_model_ort_start[];
extern const size_t melodic_model_ort_size;

#endif
